<?php

/**
 * Implements hook_block_info().
 */
function clicc_homepage_block_info() {
	$blocks['clicc_homepage'] = array(
		'info' => t('CLICC_Homepage'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
		);
	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function clicc_homepage_block_view($delta = '') {
	$block = array();
	switch ($delta) {
		case 'clicc_homepage':{
		$block['subject'] = t('');
		$block['content'] = clicc_homepage_block_contents($delta);
			break;
		}
	}
	return $block;
}

/**
 * Implements hook_block_contents().
 */
function clicc_homepage_block_contents($delta) {

	// Include helper functions
	include 'clicc_homepage_helper_functions.php';
	$html = '';
	// Note: The following is indented/formatted as if it's HTML code so we can clearly see the divisions
	// There are 3 columns in the homepage, all which are contained within a home container div

	////////////////////
	/// Home container
	////////////////////

	$html .= '
	<div id="home-container">';
				
	////////////////////
	/// Left Column
	////////////////////

	// Static Content
	$html .= '
		<div id="home-left">
			<img src="/drupal/sites/default/files/Left-Home.jpg" align="center">
			<h2>CLICC Lab/Commons</h2>
			<h6>145 Powell Library Building</h6>
			<p>The College Library Instructional Computing Commons (CLICC) offers students 100 workstations, instructional software, printers and helpful staff.</p>
			<div id="home-study-room-availability">
				<h3>Study Room Availability</h3>';
	// Powell Availability dynamic content: Displays whether or not study rooms in Powell are available
				$powSchedule = new Schedule("Powell");
				$powOpening = $powSchedule->nextOpenReservation();
				if ($powOpening == 0) {
					$html .= '
					<div id="home-availability" style="background-color:#33CC00;padding:10px;color:#E6E6E6;">
					<strong>Powell: <em>Now</em></strong>
					</div>';
				}
				else if ($powOpening >= 24) {
					$html .= '
					<div id="home-availability" style="background-color:#FF4040;padding:10px;">
					<strong>Powell: <em>In 24 Hours</em></strong>
					</div>';
				}
				else {
					$html .= '
					<div id="home-availability" style="background-color:#FFFF7D;padding:10px;color:#E6E6E6;">
					<strong>Powell: <em>In ' . $powOpening/2 . ' Hours</em></strong>
					</div>';
				}
	// YRL Availability dynamic content: Displays whether or not study rooms in YRL are available
				$yrlSchedule = new Schedule("YRL");
				$yrlOpening = $yrlSchedule->nextOpenReservation();
				if ($yrlOpening == 0) {
					$html .= '
					<div id="home-availability" style="background-color:#33CC00;padding:10px;color:#E6E6E6;">
					<strong>YRL: <em>Now</em></strong>
					</div>';
				}
				else if ($yrlOpening >= 24) {
					$html .= '
					<div id="home-availability" style="background-color:#FF4040;padding:10px;">
					<strong>YRL: <em>In 24 Hours</em></strong>
					</div>';
				}
				else {
					$html .= '
					<div id="home-availability" style="background-color:#FFFF7D;padding:10px;color:#E6E6E6;">
					<strong>YRL: <em>In ' . $yrlOpening/2 . ' Hours</em></strong>
					</div>';
				}
	// Links: "Group Study Spaces", "How to Log In", and "How to Print"
	$html .= '
			</div>
			<p>
			<div style="background-color:#ECF5FD;padding:10px;">
				<ul>
					<li><a href="group-study-spaces">Group Study Spaces</a></li>
					<li><a href="overview-and-use">How to Log In</a></li>
					<li><a href="printers">How to Print</a></li>
				</ul>
			</div>
		</div>';
				
	////////////////////
	/// Right Column
	////////////////////

	// Static content
	$html .= '	
		<div id="home-right">
			<img src="/drupal/sites/default/files/Right-Home.jpg" align="center">
			<h2>Laptop Lending</h2>
			<h6>Throughout the UCLA Libraries</h6>
			<p>Currently enrolled UCLA Students, currently employed UCLA Faculty and staff members with a BruinCard or photo ID may check out a laptop using their UCLA Logon and password.</p>
			<div id="home-most-laptops">
				<h3>Laptop Availability</h3>';
	// Most Laptops dynamic content: shows which library has the most laptops and how many they have	
				$laptop_array = get_laptops_array();
				$podname = '';
				$maxlaptops = -1;
				// Find the pod with the greatest laptop count
				for($i=0;$i<count($laptop_array);$i++)
				{
					if($laptop_array[$i]["count"] > $maxlaptops)
					{
						$podname = $laptop_array[$i]['location'];
						$maxlaptops = $laptop_array[$i]['count'];
					}
				}
	$html .= '
				<div id="most-laptops" style="background-color:#7FD9D9;padding:10px;color:#E6E6E6;">
				<strong>' . $podname . ' has the most laptops. They have: <em>' . $maxlaptops . '</em></strong>
				</div>';
	// Links: "Check out a Laptop", "Renew a Laptop", and "Print from a Laptop"
	$html .= '
			</div>
			<p>
			<div style="background-color:#ECF5FD;padding:10px;">
				<ul>
					<li><a href="borrow-laptop">Check Out a Laptop</a></li>
					<li><a href="borrow-laptop">Renew a Laptop</a></li>
					<li><a href="borrow-laptop">Print from a Laptop</a></li>
				</ul>
			</div>
		</div>';
				
	////////////////////
	/// Center Column
	////////////////////

	// Static content
	$html .= '
		<div id="home-center">
			<img src="/drupal/sites/default/files/Center-Home.jpg" align="center">
			<h2>Classrooms</h2>
			<h6>Third Floor of Powell Library Building</h6>
			<p>The CLICC Classrooms are three electronic learning spaces with desktop stations and laptops, as well as other instructional equipment and services.</p>
			<div id="home-classroom-availability">
				<h3>Classroom Availability</h3>';
				// Classroom Availability dynamic content: Shows whether or not classrooms are available for drop-in's at:
				// Powell, 3rd floor, Classrooms A, B, and C
				// YRL, RC Classroom (Research Commons
				$now = date('l');
				$classrooma_available_now = true;
				$classroomrc_available_now = true;	
				if ($now == 'Saturday' || $now == 'Sunday'){
					$classroomb_available_now = false;
					$classroomc_available_now = false;
					$classrooma_available_now = false;
					$classroomrc_available_now = false;	
				}
				else {
					// $jsonObjectA = json_decode(file_get_contents("http://webservices-dev.library.ucla.edu/irma/schedules/classrooms/today/ClassroomA"), true);
					$jsonObjectB = json_decode(file_get_contents("http://webservices-dev.library.ucla.edu/irma/schedules/classrooms/today/ClassroomB"), true);
					$jsonObjectC = json_decode(file_get_contents("http://webservices-dev.library.ucla.edu/irma/schedules/classrooms/today/ClassroomC"), true);
					// $jsonObjectRC = json_decode(file_get_contents("http://webservices-dev.library.ucla.edu/irma/schedules/classrooms/today/ClassroomRC"), true);
					$classroomb_available_now = true;
					
					if ($jsonObjectB != 'null'){
						if (sizeof($jsonObjectB['classes']) == 14 && empty($jsonObjectB['classes'][14])){
							$class = $jsonObjectB['classes'];
							$now = date('Y-m-d H-i');
							
							$classBeg = $jsonObjectB['classes']['startDate'];
							$classEnd = $jsonObjectB['classes']['endDate'];
							if($now >= $classBeg && $now <= $classEnd){
								$classroomb_available_now = false;
							}
							
						}
						else if (sizeof($jsonObjectB['classes']) != 0){
							for($i = 0; $i < sizeof($jsonObjectB['classes']); $i++){
								
									$now = date('Y-m-d H:m');
									$classBeg = $jsonObjectB['classes'][$i]['startDate'];
									$classEnd = $jsonObjectB['classes'][$i]['endDate'];
									
									if($now >= $classBeg && $now <= $classEnd){
										$classroomb_available_now = false;
									}
									
								
							}
						}
					}
					$classroomc_available_now = true;
					if ($jsonObjectC != 'null'){
						if (sizeof($jsonObjectC['classes']) == 14 && empty($jsonObjectC['classes'][14][0])){
							$class = $jsonObjectC['classes'];
							$now = date('Y-m-d H-i');
							$classBeg = $jsonObjectC['classes']['startDate'];
							$classEnd = $jsonObjectC['classes']['endDate'];
							if($now >= $classBeg && $now <= $classEnd){
								$classroomc_available_now = false;
							}
							
						}
						else if (sizeof($jsonObjectC['classes']) != 0){
							
							for($i = 0; $i < sizeof($jsonObjectC['classes']); $i++){
								
									$now = date('Y-m-d H:m');
									$classBeg = $jsonObjectC['classes'][$i]['startDate'];
									$classEnd = $jsonObjectC['classes'][$i]['endDate'];
									if($now >= $classBeg && $now <= $classEnd){
										$classroomc_available_now = false;
									}
									
							}
						}
					}
				}
				$now = date('H');
				$nowStr = strftime($now);
				$nowInt = (int)$now;
				$openCloseArr = checkOpenCloseTime("Classrooms");
				$nowInt;
				if ($nowInt < $openCloseArr['open'] || $nowInt >= $openCloseArr['close']){
					$classroomb_available_now = false;
					$classroomc_available_now = false;
					$classrooma_available_now = false;
					$classroomrc_available_now = false;
				}
				// Classroom A
				if ($classrooma_available_now) {
					$html .= '
					<div id="home-classroom-a" style="background-color:#CC6600;padding:10px;color:#E6E6E6;">
					<strong>Classroom A: <em>Class Use Only</em></strong>
					</div>';
				}
				else {
					$html .= '
					<div id="home-classroom-a" style="background-color:#FF4040;padding:10px;color:#E6E6E6;">
					<strong>Classroom A: <em>Closed</em></strong>
					</div>';
				}
				// Classroom B
				if ($classroomb_available_now) {
					$html .= '
					<div id="home-classroom-b" style="background-color:#33CC00;padding:10px;color:#E6E6E6;">
					<strong>Classroom B: <em>Open</em></strong>
					</div>';
				}
				else {
					$html .= '
					<div id="home-class-room-b" style="background-color:#FF4040;padding:10px;color:#E6E6E6;">
					<strong>Classroom B: <em>Closed</em></strong>
					</div>';
				}
				// Classroom C
				if ($classroomc_available_now) {
					$html .= '
					<div id="home-classroom-c" style="background-color:#33CC00;padding:10px;color:#E6E6E6;">
					<strong>Classroom C: <em>Open</em></strong>
					</div>';
				}
				else {
					$html .= '
					<div id="home-classroom-c" style="background-color:#FF4040;padding:10px;color:#E6E6E6;">
					<strong>Classroom C: <em>Closed</em></strong>
					</div>';
				}
				// Classroom RC
				if ($classroomrc_available_now) {
					$html .= '
					<div id="home-classroom-rc" style="background-color:#CC6600;padding:10px;color:#E6E6E6;">
					<strong>RC Classroom: <em>Class Use Only</em></strong>
					</div>';
				}
				else {
					$html .= '
					<div id="home-classroom-rc" style="background-color:#FF4040;padding:10px;color:#E6E6E6;">
					<strong>RC Classroom: <em>Closed</em></strong>
					</div>';
				}
	// Links: "Software Shortcut", "Hours and Help", and "Instructional Technology"
	$html .= '
			</div>
			<p>
			<div style="background-color:#ECF5FD;padding:10px;">
				<ul>
					<li><a href="http://shortcut.clicc.ucla.edu">Software Shortcut</a></li>
					<li><a href="hours-and-help">Hours and Help</a></li>
					<li><a href="instructional-technology">Instructional Technology</a></li>
				</ul>
			</div>
		</div>';
					
	////////////////////
	/// End of container
	////////////////////

	$html .= '
	</div>';
				
	// Return entire html string to be displayed
	return $html;

}

?>
